version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db_1:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: user818/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media
    depends_on:
      - db_1
  frontend:
    env_file: .env
    image: user818/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: user818/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
